#!/usr/bin/env node
/**
 * Bakes the barman's vectorised frames into src/generated/barman.ts.
 *
 * The frames are drawn and vectorised in the sibling beer-counter-graphics
 * repo (tools/vec, out/vec/final): seven head frames and nine hand frames,
 * each a white "paper" path and a black "ink" path on a transparent sheet.
 * Baking them into a module keeps the app buildable from a clone without the
 * graphics repo and lets the component recolour the ink with currentColor.
 *
 *   yarn barman:import                 # from ../beer-counter-graphics/out/vec/final
 *   yarn barman:import path/to/frames  # from somewhere else
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, process.argv[2] ?? '../beer-counter-graphics/out/vec/final');

const HEAD_FRAMES = 7; // neutral, three looking around, three of the slow gesture
const HAND_FRAMES = 9; // three ways of shaking × three positions

/** One path's data, trimmed to a tenth of a sprite pixel: plenty at the size he is drawn. */
function round(d) {
  return d.replace(/\d+\.\d+/g, (n) => String(Math.round(Number(n) * 10) / 10));
}

function frame(name) {
  let svg;
  try {
    svg = readFileSync(resolve(source, `${name}.svg`), 'utf8');
  } catch {
    console.error(`${name}.svg not found in ${source} — is beer-counter-graphics checked out beside this repo?`);
    process.exit(1);
  }
  const paths = Object.fromEntries(
    [...svg.matchAll(/<path fill="(#fff|#000)"[^>]*? d="([^"]*)"/g)].map(([, fill, d]) => [fill, round(d)]),
  );
  if (!paths['#fff'] || !paths['#000']) {
    console.error(`${name}.svg: expected one #fff and one #000 path`);
    process.exit(1);
  }
  const [, w, h] = /viewBox="0 0 (\d+) (\d+)"/.exec(svg) ?? [];
  return { paper: paths['#fff'], ink: paths['#000'], w: Number(w), h: Number(h) };
}

/**
 * The columns the drawing actually covers, across every frame, so the component can
 * crop BAR's 184-column strip to him. Every number in the path data is a coordinate
 * (absolute commands only), so the extremes of the x values bound the ink; control
 * points can only widen that, which is the safe direction.
 */
function span(frames, offset) {
  let left = Infinity;
  let right = -Infinity;
  for (const f of frames) {
    // Only M, C and Z occur, all absolute: strip the letters and every
    // even-numbered value left is an x.
    const values = (f.paper + " " + f.ink).replace(/[A-Za-z]/g, " ").trim().split(/\s+/).map(Number);
    for (let i = 0; i < values.length; i += 2) {
      left = Math.min(left, values[i] + offset);
      right = Math.max(right, values[i] + offset);
    }
  }
  return [Math.floor(left), Math.ceil(right)];
}

const heads = Array.from({ length: HEAD_FRAMES }, (_, i) => frame(`barman_${String(i).padStart(2, '0')}`));
const hands = Array.from({ length: HAND_FRAMES }, (_, i) => frame(`hand_${String(i).padStart(2, '0')}`));

const [headLeft, headRight] = span(heads, 0);
const [handLeft, handRight] = span(hands, 72); // the hand is blitted at x = 72
const content = { left: Math.min(headLeft, handLeft), right: Math.max(headRight, handRight) };

const list = (frames) =>
  frames.map((f) => `  { paper: ${JSON.stringify(f.paper)}, ink: ${JSON.stringify(f.ink)} },`).join('\n');

writeFileSync(
  resolve(root, 'src/generated/barman.ts'),
  `// Generated by scripts/import-barman.mjs — do not edit.
// Source: beer-counter-graphics/out/vec/final (barman_00..${String(HEAD_FRAMES - 1).padStart(2, '0')}, hand_00..${String(HAND_FRAMES - 1).padStart(2, '0')}).

/** One sprite frame: the white sheet behind the drawing, then the black line work. */
export interface BarmanFrame {
  paper: string;
  ink: string;
}

/** Head sprite size, in sprite pixels. */
export const HEAD_SIZE = { w: ${heads[0].w}, h: ${heads[0].h} } as const;
/** Hand (and body) sprite size, in sprite pixels. */
export const HAND_SIZE = { w: ${hands[0].w}, h: ${hands[0].h} } as const;
/** The columns of the 184-wide strip that carry ink in any frame; the rest is air. */
export const CONTENT = { left: ${content.left}, right: ${content.right} } as const;

export const HEAD_FRAMES: readonly BarmanFrame[] = [
${list(heads)}
];

export const HAND_FRAMES: readonly BarmanFrame[] = [
${list(hands)}
];
`,
);
console.log(`src/generated/barman.ts: ${heads.length} head + ${hands.length} hand frames from ${source}`);
